# Generated by Django 5.1.2 on 2024-10-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile image', null=True, upload_to='avatars/'),
        ),
    ]
