# Generated by Django 5.1.2 on 2024-10-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.SmallIntegerField(default=1),
        ),
    ]
