# Generated by Django 5.1.2 on 2024-10-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='name_uz',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
