# Generated by Django 5.1.2 on 2024-10-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productsize_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
