# Generated by Django 5.1.2 on 2024-10-29 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cartitem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 11, 21, 13, 739258, tzinfo=datetime.timezone.utc)),
        ),
    ]
