# Generated by Django 5.1.2 on 2024-10-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default='cash', max_length=20),
        ),
    ]
